---
vagrant:
  synced_folders:
    - host: "/Users/jack/Sites/drupal-training-day/web"
      guest: /var/www/drupal-training-day/htdocs
      type: nfs
    - host: "/Users/jack/.drush/aliases"
      guest: /etc/drush
ansible:
  reroute_email: jack@limoengroen.nl
