---
# file: roles/drupal/handlers/main.yml

- name: restart_apache
  service:
    name=apache2
    state=restarted

- name: restart_nginx
  service:
    name=nginx
    state=restarted

- name: drush_cc_drush
  command: /usr/local/share/drush/drush cache-clear drush

- name: restart_rsyslog
  service:
    name=rsyslog
    state=restarted