---
# file: roles/webserver/handlers/main.yml

- name: restart_apache
  service:
    name=apache2
    state=restarted

- name: restart_nginx
  service:
    name=nginx
    state=restarted

- name: restart_varnish
  service:
    name=varnish
    state=restarted

- name: restart_php-fpm
  service:
    name=php7.0-fpm
    state=restarted

- name: restart_memcached
  service:
    name=memcached
    state=restarted
