---
# file: roles/dbserver/tasks/main.yml

- name: "Install packages."
  apt:
    pkg={{ item }}
    state=installed
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: "Remove the test database."
  mysql_db:
    name=test
    state=absent

  # 'localhost' needs to be the last item for idempotency, see
  # http://ansible.cc/docs/modules.html#mysql-user
- name: "Update mysql root password for all root accounts."
  mysql_user: name=root host={{ item }} password={{ mysql_root_password | mandatory }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: "Copy .my.cnf file with root password credentials."
  template:
    src=.my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600
